services:
  - type: web
    name: whatsapp-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start:web
    envVars:
      - key: APP_ROLE
        value: web
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
      - key: DATABASE_URL
        value: postgresql://botwhatsapp_7gbj_user:ltMv03ghqgw1pwUnvP9ob4M6BGxxkM8w@dpg-d7l1n71o3t8c73b3pa5g-a.oregon-postgres.render.com/botwhatsapp_7gbj

databases:
  - name: bot-whatsapp-db
    engine: postgres
    plan: free
    ipAllowList: []
